# mpu6050_data.msg
float64 quat_w
float64 quat_x
float64 quat_y
float64 quat_z
float64 accel_x
float64 accel_y
float64 accel_z
float64 gyro_x
float64 gyro_y
float64 gyro_z

float32 accel_x         # Acceleration in x-axis
float32 accel_y         # Acceleration in y-axis
float32 accel_z         # Acceleration in z-axis
float32 gyro_x          # Gyroscope reading in x-axis
float32 gyro_y          # Gyroscope reading in y-axis
float32 gyro_z          # Gyroscope reading in z-axis